# Modo: normal — visual padrão Catppuccin Macchiato
# Incluído via ~/.config/sway/config.d/99-mode.conf

gaps inner 0
gaps outer 0

#default_border pixel 2

client.focused          #494d64 #181926 #cad3f5 #f4dbd6 #494d64
client.unfocused        #181926 #1e2030 #6e738d #181926 #181926
client.focused_inactive #363a4f #1e2030 #a5adcb #363a4f #363a4f
client.urgent           #ed8796 #ed8796 #1e2030 #ed8796 #ed8796
client.placeholder      #363a4f #1e2030 #6e738d #363a4f #363a4f
